server:
  port: 1400
  servlet:
    context-path: "/banking"

spring:
  datasource:
    url: "jdbc:mysql://localhost"
    username: "root"
    password: "deviprasad"
  sql:
    init:
      mode: ALWAYS
  jpa :
    properties:
      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update



